name: "ReachabilityBridge CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  SPM:
    name: Verify SPM build
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    strategy:
      matrix:
        destination:
          [
            "platform=iOS Simulator,name=iPhone 12 Pro",
            "platform=macOS,variant=Mac Catalyst",
          ]
        scheme: ["ReachabilityBridge"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check that current SPM passed
        run: xcodebuild clean build -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}"
